-- AI enhancement metadata for documents (#v0.9)
-- Stores per-document summaries and tags generated by Claude

ALTER TABLE documents ADD COLUMN ai_summary TEXT;
ALTER TABLE documents ADD COLUMN ai_tags TEXT;          -- JSON array of tags
ALTER TABLE documents ADD COLUMN ai_processed_at TEXT;  -- ISO 8601 timestamp
