name: Task
description: Technical work item
labels: ["infra"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
    validations:
      required: true
  - type: textarea
    id: subtasks
    attributes:
      label: Subtasks
      placeholder: |
        - [ ] ...
        - [ ] ...
